# Module and package tracebacks

Module and package tracebacks
When using functions from modules and packages, code from downloaded files will be run in the background.

If this code produces an error, the traceback will mention the name of the file in which the error occurred.

Running this code produces the following error. In what file does the error occur?

import requests
requests.get(url="https://app.datacamp.com", content=True)
Traceback from using an invalid keyword argument in the get function from the requests module

Answer the question
50XP
Possible Answers
Select one answer

base.py
Press
1

requests.py
Press
2

api.py
Press
3

The error occurs in the **`api.py`** file. When an invalid keyword argument is used in the `requests.get()` function, the traceback will point to the internal file where the issue is handled in the `requests` library, which is typically `api.py` for such errors.

So, the correct answer is:
**3. api.py**